name: 'Отчёт Кибердядьки'
description: 'GitHub action to check code styling'
inputs:
  lines-per-msg:  # id of input
    description: 'На сколько строк разрешено одно сообщение'
    required: true
    default: 200
outputs:
  tot-msgs:
    description: 'Сколько получено сообщений'
  tot-lines:
    description: 'Сколько проверено строк'
  tot-score:
    description: 'Качество кода'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.lines-per-msg }}
