name: 'Кибердядька'
description: 'GitHub action to check code styling'
inputs:
  lines-per-msg:  # id of input
    description: 'На сколько строк разрешено одно сообщение'
    required: true
    default: '100'
outputs:
  c-tot-msgs:
    description: 'Сколько сообщений по C'
  c-tot-lines:
    description: 'Сколько строк на C'
  c-tot-score:
    description: 'Сколько очков за C'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.lines-per-msg }}
