name: 'Проверка Кибердядьки'
on:
  workflow_call:
    inputs:
      lines-per-msg:
        description: 'На сколько строк разрешено одно сообщение'
        required: true
        type: number
        default: 200
    outputs:
      tot-msgs:
        description: 'Сколько получено сообщений'
        value: ${{ jobs.analyze.outputs.check-tot-msgs }}
      tot-lines:
        description: 'Сколько проверено строк'
        value: ${{ jobs.analyze.outputs.check-tot-lines }}
      tot-score:
        description: 'Качество кода'
        value: ${{ jobs.analyze.outputs.check-tot-score }}

jobs:
  analyze:
    name: 'Кибердядька проверяет'
    runs-on: ubuntu-latest
    outputs:
      check-tot-msgs: ${{ steps.cybercheck.outputs.tot-msgs }}
      check-tot-lines: ${{ steps.cybercheck.outputs.tot-lines }}
      check-tot-score: ${{ steps.cybercheck.outputs.tot-score }}
    steps:
      - uses: actions/checkout@v2
        name: 'Получение репозитория'
      - id: cybercheck
        name: 'Проверка Кибердядькой'
        uses: dluciv/cyber-under-tutor@main
        with:
          lines-per-msg: ${{ inputs.lines-per-msg }}
      - name: 'Сохранение отчёта'
        uses: actions/upload-artifact@v2
        with:
          name: analyzis-results
          path: |
            quality-check.*
          retention-days: 1
