name: 'Анализ и отчёт'
on:
  workflow_call:
    inputs:
      lines-per-msg:
        description: 'На сколько строк разрешено одно сообщение'
        required: true
        type: number
        default: 200
    outputs:
      tot-score:
        description: 'Качество кода'
        value: ${{ jobs.analyze.outputs.check-tot-score }}

jobs:
  analyze:
    name: 'Кибердядька проверяет'
    runs-on: ubuntu-latest
    outputs:
      check-tot-msgs: ${{ steps.cybercheck.outputs.tot-msgs }}
      check-tot-lines: ${{ steps.cybercheck.outputs.tot-lines }}
      check-tot-score: ${{ steps.cybercheck.outputs.tot-score }}
    steps:
      - uses: actions/checkout@v2
        name: 'Получение репозитория'
      - id: cybercheck
        name: 'Проверка Кибердядькой'
        uses: dluciv/cyber-under-tutor@main
        with:
          lines-per-msg: ${{ inputs.lines-per-msg }}
      - name: 'Сохранение отчёта'
        uses: actions/upload-artifact@v2
        with:
          name: analyzis-results
          path: |
            quality-check.*
          retention-days: 1

  report:
    needs:
      - analyze
    name: 'Кибердядька докладывает'
    runs-on: ubuntu-latest
    steps:
      - name: 'Получение ветви отчёта'
        uses: actions/checkout@v2
        with:
          ref: 'cyber-under-tutor'
      - name: 'Получение отчёта'
        uses: actions/download-artifact@v2
        with:
          name: analyzis-results
          path: .
      - name: 'Публикация отчёта'
        run: |
          pip3 install anybadge
          git config user.email "CYBER@DRDbKA.github.com"
          git config user.name "Кибердядька"

          SCORE_PERCENT=$(bc <<< scale=0; ${{ needs.analyze.outputs.check-tot-score }}/0.01)
          echo "::notice ::Score: ${SCORE_PERCENT}%"
          anybadge -l 'Кибердядька' -d 1 -v $SCORE_PERCENT -s '%' -f quiality-check.svg 0=red 50=orange 75=yellow 1000=green
          git add quality-check.*

          git commit -m "Кибердядька сообщает"
          git push
