name: 'Отчёт и бэйдж Кибердядьки'
on:
  workflow_call:
    inputs:
      lines-per-msg:
        description: 'На сколько строк разрешено одно сообщение'
        required: true
        type: number
        default: 200
    outputs:
      tot-msgs:
        description: 'Сколько получено сообщений'
        value: ${{ jobs.check-and-report.outputs.check-tot-msgs }}
      tot-lines:
        description: 'Сколько проверено строк'
        value: ${{ jobs.check-and-report.outputs.check-tot-lines }}
      tot-score:
        description: 'Качество кода'
        value: ${{ jobs.check-and-report.outputs.check-tot-score }}
jobs:
  check-and-report:
    name: 'Кибердядька докладывает'
    runs-on: ubuntu-latest
    outputs:
      check-tot-msgs: ${{ steps.cybercheck.outputs.tot-msgs }}
      check-tot-lines: ${{ steps.cybercheck.outputs.tot-lines }}
      check-tot-score: ${{ steps.cybercheck.outputs.tot-score }}
    steps:
      - uses: actions/checkout@v2
        name: 'Получение репозитория'
      - id: cybercheck
        name: 'Проверка'
        uses: dluciv/cyber-under-tutor@main
        with:
          lines-per-msg: ${{ inputs.lines-per-msg }}
      - name: 'Сохранение отчёта'
        run: |
          mv quality-check.yml quality-check.svg $TMPDIR
      - name: 'Получение ветви отчёта'
        uses: actions/checkout@v2
        with:
          ref: 'cyber-under-tutor'
      - name: 'Публикация отчёта'
        run: |
          git config user.email "CYBER@DRDbKA.github.com"
          git config user.name "Кибердядька"

          mv $TMPDIR/quality-check.yml $TMPDIR/quality-check.svg .

          git add quality-check.yml quality-check.svg
          git commit -m "Кибердядька сообщает"
          git push
